### ISSUE TITLE
FAQ 

### ISSUE THREAD

**Issue by Ericaward** [savethehopestationhouse/savethehopestationhouse.github.io#1]
Hi April, in line with previous communications and as per 5th March meeting please could we add the FAQ document in some form to the website. Thanks and appreciate your time, Erica

### Assertion criteria
- [x] faqs.pdf has been uploaded to the website
- [x] faqs.pdf is linked to from `index.html`

### Document
[faqs.pdf](https://github.com/savethehopestationhouse/savethehopestationhouse.github.io/files/6152646/faqs.pdf)

**Comment by savethehopestationhouse** [comment]
@Ericaward - completed.  Sorry on the delay.  Was going to create a new page for it, but given lack of time I went with mvp solution of uploading and linking to the pdf: https://www.savethehopestationhouse.ca/documents/faqs.pdf

### Screenshot of the link to the FAQs
- Added a link to the FAQs at the top of the landing page.  
- Can circle back and increase font size and such to make it stand out more so, but still not compete with the "call to action" (`CLICK HERE to learn how you can help save it!`)

<img width="598" alt="Screen Shot 2021-03-16 at 3 28 55 PM" src="https://user-images.githubusercontent.com/77593823/111388359-57a5b680-866c-11eb-9e86-80c3ac8eb363.png">

**Comment by Ericaward** [comment]
Hi April,

Thanks so much, but it looks like this is the Timeline not the FAQs. Not averse to having the timeline too, though, but the FAQ is to help with ‘myth busting’ and is referenced in the flyer. The correct attachment is the one in my email on March 12th. It’s a Word version with a couple of highlights that would need removing before making into a PDF.

Let me know if you need anything else!

Thanks
Erica

Erica Ward
________________________________

**Comment by savethehopestationhouse** [comment]
@Ericaward - could you send along that FAQs pdf?  Sorry, I thought I was grabbing the right doc.  I've got 15 min before a meeting so I can quickly upload the correct doc if you send it along.  You can even upload to one of these comments using the `Attach files by dragging & dropping, selecting or pasting them` link at the bottom of the comment window.

**Comment by Ericaward** [comment]
No problem here it is
________________________________

**Comment by savethehopestationhouse** [comment]
oh sorry, I meant the PDF :)  You can also just email it to me if that's easier.

**Comment by savethehopestationhouse** [comment]
@Ericaward - fixed.  Please check and confirm. https://www.savethehopestationhouse.ca/documents/faqs.pdf

The timeline is still up there at https://www.savethehopestationhouse.ca/documents/timeline.pdf

**Comment by Ericaward** [comment]
Yes that looks good, thank you!
________________________________
